### ISSUE TITLE
Oct 28 TODO

### ISSUE THREAD

**Issue by dicook** [KrisanatA/animbook-journal#10]
- [x] Format lines of code so they stay within page
- [x] Check that all spelling is either American or Australian. There is a mixture currently "behaviour" is Australian, but "visualization" is American.
- [x] The bullet lists for `anim_prep` and `anim_prep_cat` are quite long, and have common arguments. Maybe have one list explaining the arguments common to both functions, and then two smaller separate bullet lists of the special features of each.
- [x] In the data pre-processing I don't se much difference in the data from 1, 2, 3, 4. Maybe you can organise these into a table, and highlight the lines that are different when the different scaling is applied. Alternatively, just make one table of numbers, with multiple columns, one for each of the different scaling. The primary goal is to illustrate the effect of the scaling choices. So make this easy to read. 
- [x] In the 6.3 Example usage section, add some more explanation of each step, an opening paragraph, and a full sentence explanation at each step. (Maybe this was on your list to do already.)
- [x] For Figures 7 and 8, add some details on what is learned about the data to the caption. Eg Mostly voters remain loyal to the party, but a small fraction of voters in roughly equal male to female ratio switch, primarily to the other major party.
- [x] 8 Summary could have some more possible directions for the work to develop.
