### ISSUE TITLE
Oct 29 TODO

### ISSUE THREAD

**Issue by dicook** [KrisanatA/animbook-journal#11]
- [x] The NYTimes animation is used for motivation but it doesn't strictly define your animation, so you only need to refer to it in the Intro, and when you explain how it was created. You can remove references to it from the Design and Software sections.
- [x] I don't think you need the paragraph on tidy data at the start of the Data section. A single sentence referring to tidy data, with the citation, is probably sufficient. 
- [x] Any package needs to be referred to with \CRANpkg{}, at every reference, just check this. I've made some changes. (Or \pkg{} if it is not on CRAN.)
- [x] Only cite a package the first time you refer to it.
- [x] Expand the captions of the later figures, like I have done with figures 1 and 2.
