### ISSUE TITLE
Oct 29 TODO

### ISSUE THREAD

**Issue by dicook** [KrisanatA/animbook-journal#12]
- [x] Is there a reference to cite for Sankey diagrams?
- [x] The interpretation of Figure 10 is different between the caption and the text. The text focuses on the change of "others" to the Green Party. But I don't see this. There are few green points, and you see a few drop from liberals to greens but there seem to be more in the group that runs from liberal to liberal. When I wrote the caption the main things I saw were the persistence in remaining with the same party, and if they switch it is to the other main party. Maybe with different colours where the "others" stands out there might be a more visible shift. Maybe the article where you pulled the data from emphasised the relationship you report? But it's not supported by the visualisation. Also, the last statement about liberals needing to consider campaign focus change isn't supportable - focusing on LGBTIQ+ could also lead to a further defection of conservative voters. Adjust this paragraph a little. 
- [x] Osiris citation needs a year. Typically you would use the year when you extract the sample, so 2023.
- [x] Would you be able to do a different wallaby plot on the Osiris data? To see the movement to de-listing the kangaroo plot is better. For the wallaby plot, the result is confounded, because there might be fewer Japanese companies anyway, so you can't tell whether more American companies get de-listed. Perhaps something like the bottom 25% in 2006 to see where they go in 2018?
